export const jobRoles = {
  'Frontend Developer': {
    title: 'Frontend Developer',
    keywords: [
      'react',
      'javascript',
      'typescript',
      'html',
      'css',
      'tailwind',
      'redux',
      'router',
      'api',
      'responsive',
      'accessibility',
    ],
    skillRecommendations: ['React', 'TypeScript', 'Accessibility', 'Performance Optimization', 'Testing'],
  },
  'MERN Developer': {
    title: 'MERN Developer',
    keywords: [
      'mongodb',
      'express',
      'react',
      'node',
      'javascript',
      'rest api',
      'jwt',
      'mongoose',
      'authentication',
      'deployment',
    ],
    skillRecommendations: ['MongoDB', 'Express.js', 'Node.js', 'React', 'System Design'],
  },
  'Software Engineer': {
    title: 'Software Engineer',
    keywords: [
      'algorithms',
      'data structures',
      'system design',
      'testing',
      'debugging',
      'clean code',
      'api',
      'database',
      'cloud',
      'git',
    ],
    skillRecommendations: ['System Design', 'Testing', 'Cloud Basics', 'DSA', 'Design Patterns'],
  },
  'Data Analyst': {
    title: 'Data Analyst',
    keywords: [
      'excel',
      'sql',
      'python',
      'power bi',
      'tableau',
      'statistics',
      'dashboard',
      'data visualization',
      'reporting',
      'analysis',
    ],
    skillRecommendations: ['SQL', 'Excel', 'Power BI', 'Statistics', 'Data Visualization'],
  },
};

export const getRoleProfile = (roleName) => jobRoles[roleName] || jobRoles['Software Engineer'];